version: '3.8'

networks:
  aspire_network:
    external: true

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_NODES_INCLUDE=n8n-nodes-base,n8n-nodes-mmlib
      - N8N_LOG_LEVEL=debug
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - aspire_network
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-nodes-mmlib/dist:/home/node/.n8n/custom/node_modules/n8n-nodes-mmlib

volumes:
  n8n_data: 